blank_issues_enabled: true
contact_links:
  - name: Commercial licensing or written permissions
    url: https://github.com/GnollStack/Squad-Combat-Initiative#contact
    about: Please contact GnollStack directly by Discord for commercial licensing or written permission requests.
